/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
import java.sql.*;
import javax.swing.JOptionPane;
import lib.koneksi;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;

/**
 *
 * @author ASUS VIVOBOOK
 */
public class FEditDosen extends javax.swing.JInternalFrame {
koneksi konek = new koneksi ();
private ActionEvent evt;
String pilNIDN, pilNamaDosen, pilTempatLahir, pilJenisKelamin, pilAlamat, pilNoTlp, pilEmail, pilPendidikanTerakhir, pilKonsentrasi, pilPangkat, pilGolongan;

    /**
     * Creates new form FEditDosen
     */
    public FEditDosen() {
        initComponents();
        btRefreshActionPerformed(evt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfNIDN = new javax.swing.JTextField();
        tfNamaDosen = new javax.swing.JTextField();
        tfTempatLahir = new javax.swing.JTextField();
        tfJK = new javax.swing.JTextField();
        tfAlamat = new javax.swing.JTextField();
        tfNoTlp = new javax.swing.JTextField();
        tfPendidikan = new javax.swing.JTextField();
        tfKonsentrasi = new javax.swing.JTextField();
        tfPangkat = new javax.swing.JTextField();
        tfGolongan = new javax.swing.JTextField();
        dcTanggal = new com.toedter.calendar.JDateChooser();
        jTBEditDosen = new javax.swing.JScrollPane();
        jTBDosen = new javax.swing.JTable();
        btUbah = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        btHapus = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Form Edit Dosen");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("EDIT DOSEN");

        jLabel1.setText("NIDN");

        jLabel3.setText("Nama Dosen");

        jLabel4.setText("Tempat Lahir");

        jLabel5.setText("Tanggal Lahir");

        jLabel6.setText("Jenis Kelamin");

        jLabel7.setText("Alamat");

        jLabel8.setText("No. Tlp");

        jLabel9.setText("Pendidikan Terakhir");

        jLabel10.setText("Konsetrasi");

        jLabel11.setText("Pangkat");

        jLabel12.setText("Golongan");

        tfTempatLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTempatLahirActionPerformed(evt);
            }
        });

        tfAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlamatActionPerformed(evt);
            }
        });

        jTBDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "NIDN", "Nama Dosen", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Alamat", "No.Tlp", "Email", "Pendidikan Terakhir", "Konsentrasi", "Pangkat", "Golongan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTBDosen.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTBDosenAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTBDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBDosenMouseClicked(evt);
            }
        });
        jTBEditDosen.setViewportView(jTBDosen);

        btUbah.setText("Ubah");
        btUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUbahActionPerformed(evt);
            }
        });

        btRefresh.setText("Refresh");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        jLabel13.setText("Email");

        btHapus.setText("Hapus");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTBEditDosen)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNIDN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfJK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(430, 430, 430))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addGap(72, 72, 72)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(tfGolongan)
                                                        .addComponent(tfPangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addGap(61, 61, 61)
                                                    .addComponent(tfKonsentrasi, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel12)
                                                    .addGap(298, 298, 298))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel13))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(tfPendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(77, 77, 77)
                                                    .addComponent(tfNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(151, 151, 151))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btHapus)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel7))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRefresh)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfNIDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(tfNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(tfTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dcTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btUbah)
                            .addComponent(btHapus)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfPendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfKonsentrasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfPangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tfGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTBEditDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAlamatActionPerformed

    private void tfTempatLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTempatLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTempatLahirActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
    DefaultTableModel tabeldosen = new DefaultTableModel();
        tabeldosen.addColumn("No");
        tabeldosen.addColumn("ID");
        tabeldosen.addColumn("NIDN");
        tabeldosen.addColumn("Nama Dosen");
        tabeldosen.addColumn("Tempat Lahir");
        tabeldosen.addColumn("Tanggal Lahir");
        tabeldosen.addColumn("Jenis Kelamin");
        tabeldosen.addColumn("Alamat");
        tabeldosen.addColumn("No. Tlp");
        tabeldosen.addColumn("Email");
        tabeldosen.addColumn("Pendidikan Terakhir");
        tabeldosen.addColumn("Konsentrasi");
        tabeldosen.addColumn("Pangkat");
        tabeldosen.addColumn("Golongan");
        
        try{ //PENGUJIAN
        String sql = "Select * from daftar_dosen ";
        Statement st = konek.getKoneksi().createStatement();
        ResultSet hasil = st.executeQuery(sql);
        int no = 0;
        
        tabeldosen.setRowCount(0); // Menghapus semua baris sebelum menambahkan yang baru
        while(hasil.next()){
            no = no + 1;
            tabeldosen.addRow(new Object[]{no, hasil.getString(1), hasil.getString(2), hasil.getString(3), hasil.getString(4), hasil.getString(5), hasil.getString(6), hasil.getString(7), hasil.getString(8), hasil.getString(9), hasil.getString(10), hasil.getString(11), hasil.getString(12), hasil.getString(13)});
}

        
     
    jTBDosen.setModel(tabeldosen);
        }catch(Exception e){//JIKA TIDAK BERHASIL
        JOptionPane.showMessageDialog(this, "Kesalahan : " + e);
    
        }
    }//GEN-LAST:event_btRefreshActionPerformed

    private void btUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUbahActionPerformed
        String nidn = pilNIDN;
        String nama_dosen = tfNamaDosen.getText(); 
        String tempat_lahir = tfTempatLahir.getText();
        String tgl_lahir = new SimpleDateFormat("yyyy-MM-dd").format(dcTanggal.getDate());
        String jenis_kelamin = tfJK.getText();
        String alamat = tfAlamat.getText();
        String no_hp = tfNoTlp.getText();
        String email = tfEmail.getText();
        String pendidikan_terakhir = tfPendidikan.getText();
        String konsentrasi = tfKonsentrasi.getText();
        String pangkat = tfPangkat.getText();
        String golongan = tfGolongan.getText();
        
         if (!nidn.isEmpty() && !nama_dosen.isEmpty()) {
        String sql = "UPDATE daftar_dosen SET nama_dosen='"+nama_dosen+"', tempat_lahir='"+tempat_lahir+"', tgl_lahir='"+tgl_lahir+"', jenis_kelamin='"+jenis_kelamin+"', alamat='"+alamat+"', no_hp='"+no_hp+"', email='"+email+"', pendidikan_terakhir='"+pendidikan_terakhir+"', konsentrasi='"+konsentrasi+"', pangkat='"+pangkat+"', golongan='"+golongan+"' WHERE nidn='"+nidn+"'";

        try {
            Statement s = konek.getKoneksi().createStatement();
            s.executeUpdate(sql);
            s.close();
            JOptionPane.showMessageDialog(this, "Data Dosen Berhasil Diubah");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Dosen Gagal Diubah: " + e);
        }
    } else {
        JOptionPane.showMessageDialog(this, "NIDN dan Nama Dosen harus di isi dengan benar." ); 
    }
        this.btRefreshActionPerformed(evt);
        tfNIDN.setText("");
        tfNamaDosen.setText("");
        tfTempatLahir.setText("");
        tfJK.setText("");
        tfAlamat.setText("");
        tfNoTlp.setText("");
        tfEmail.setText("");
        tfPendidikan.setText("");
        tfKonsentrasi.setText("");
        tfPangkat.setText("");
        tfGolongan.setText("");
    }//GEN-LAST:event_btUbahActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
    String hapus = "DELETE FROM daftar_dosen WHERE nidn='" + pilNIDN + "'";
if (JOptionPane.showConfirmDialog(null, "Apakah anda yakin menghapus data " + pilNIDN + " ini?", "information",
        JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.OK_OPTION) {
    try {
        Connection connection = konek.getKoneksi();
        String sql = "DELETE FROM daftar_dosen WHERE nidn=?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            preparedStatement.setString(1, pilNIDN);

            int rowsAffected = preparedStatement.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                this.btRefreshActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Terjadi Kesalahan: " + e);
    }
} else {
    this.btRefreshActionPerformed(evt);
    tfNIDN.setText("");
    tfNamaDosen.setText("");
    tfTempatLahir.setText("");
    tfJK.setText("");
    tfAlamat.setText("");
    tfNoTlp.setText("");
    tfEmail.setText("");
    tfPendidikan.setText("");
    tfKonsentrasi.setText("");
    tfPangkat.setText("");
    tfGolongan.setText("");
}

    }//GEN-LAST:event_btHapusActionPerformed

    private void jTBDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBDosenMouseClicked
    int i = this.jTBDosen.getSelectedRow();
        if(i==-1){
            return;
        }
        pilNIDN = (String) this.jTBDosen.getValueAt(i, 2);
        tfNIDN.setText(pilNIDN);
        pilNamaDosen = (String) this.jTBDosen.getValueAt(i, 3);
        tfNamaDosen.setText(pilNamaDosen);
        pilTempatLahir = (String) this.jTBDosen.getValueAt(i, 4);
        tfTempatLahir.setText(pilTempatLahir);
        pilJenisKelamin = (String) this.jTBDosen.getValueAt(i, 6);
        tfJK.setText(pilJenisKelamin);
        pilAlamat = (String) this.jTBDosen.getValueAt(i, 7);
        tfAlamat.setText(pilAlamat);
        pilNoTlp = (String) this.jTBDosen.getValueAt(i, 8);
        tfNoTlp.setText(pilNoTlp);
        pilEmail = (String) this.jTBDosen.getValueAt(i, 9);
        tfEmail.setText(pilEmail);
        pilPendidikanTerakhir = (String) this.jTBDosen.getValueAt(i, 10);
        tfPendidikan.setText(pilPendidikanTerakhir);
        pilKonsentrasi = (String) this.jTBDosen.getValueAt(i, 11);
        tfKonsentrasi.setText(pilKonsentrasi);
        pilPangkat = (String) this.jTBDosen.getValueAt(i, 12);
        tfPangkat.setText(pilPangkat);
        pilGolongan = (String) this.jTBDosen.getValueAt(i, 13);
        tfGolongan.setText(pilGolongan);
    }//GEN-LAST:event_jTBDosenMouseClicked

    private void jTBDosenAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTBDosenAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBDosenAncestorMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btUbah;
    private com.toedter.calendar.JDateChooser dcTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTable jTBDosen;
    private javax.swing.JScrollPane jTBEditDosen;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfGolongan;
    private javax.swing.JTextField tfJK;
    private javax.swing.JTextField tfKonsentrasi;
    private javax.swing.JTextField tfNIDN;
    private javax.swing.JTextField tfNamaDosen;
    private javax.swing.JTextField tfNoTlp;
    private javax.swing.JTextField tfPangkat;
    private javax.swing.JTextField tfPendidikan;
    private javax.swing.JTextField tfTempatLahir;
    // End of variables declaration//GEN-END:variables
}
