/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author ASUS VIVOBOOK
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lib.koneksi;

public class FTampilMK extends javax.swing.JInternalFrame {
    koneksi konek = new koneksi ();
    /**
     * Creates new form FTampilMK
     */
    public FTampilMK() {
        initComponents();
        tampilmk();
    }
    
    public void tampilmk() {
        DefaultTableModel tabelmk = new DefaultTableModel();
        tabelmk.addColumn("No");
        tabelmk.addColumn("ID MK");
        tabelmk.addColumn("Kode MK");
        tabelmk.addColumn("Nama MK");
        tabelmk.addColumn("Kredit");
        tabelmk.addColumn("Prasyarat");
        tabelmk.addColumn("Status");
        tabelmk.addColumn("Tahun Semester");
    try {
        String sql = "Select * from daftar_mk ";
        Statement st = konek.getKoneksi().createStatement();
        ResultSet hasil = st.executeQuery(sql);
        int no = 0;
        while (hasil.next()) {
            no = no + 1;
            tabelmk.addRow(new Object[]{no, hasil.getString(1), hasil.getString(2), hasil.getString(3), hasil.getString(4), hasil.getString(5), hasil.getString(6), hasil.getString(7)});
        }
        jTBMK.setModel(tabelmk); // jTBMatkul adalah nama tabel untuk menampilkan data mata kuliah
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Kesalahan : " + e);
    }
}

private void cariMK() {
    DefaultTableModel tabelmk = new DefaultTableModel();
    tabelmk.addColumn("No");
    tabelmk.addColumn("Kode MK");
    tabelmk.addColumn("Nama Mk");
    tabelmk.addColumn("Kredit");
    tabelmk.addColumn("Prasyarat");
    tabelmk.addColumn("Status");
    tabelmk.addColumn("Tahun Semester");

    try {
        String sql = "Select * from daftar_mk where nama_mk LIKE '%" + tfKunciMK.getText() + "%'";
        Statement st = konek.getKoneksi().createStatement();
        ResultSet hasil = st.executeQuery(sql);
        int no = 0;
        while (hasil.next()) {
            no = no + 1;
            tabelmk.addRow(new Object[]{no, hasil.getString(1), hasil.getString(2), hasil.getString(3), hasil.getString(4), hasil.getString(5), hasil.getString(6), hasil.getString(7)});
        }
        jTBMK.setModel(tabelmk);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Kesalahan : " + e);
    }
}
   
        
        
        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfKunciMK = new javax.swing.JTextField();
        btCariMK = new javax.swing.JButton();
        btRefreshMK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBMK = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Form Data Mata Kuliah");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DATA MATA KULIAH");

        jLabel2.setText("Cari Mata Kuliah");

        btCariMK.setText("Cari");
        btCariMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariMKActionPerformed(evt);
            }
        });

        btRefreshMK.setText("Refresh");
        btRefreshMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshMKActionPerformed(evt);
            }
        });

        jTBMK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID MK", "Kode MK", "Nama MK", "Kredit", "Prasyarat", "Status", "Tahun Semester"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTBMK);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfKunciMK)
                                .addGap(18, 18, 18)
                                .addComponent(btCariMK)
                                .addGap(18, 18, 18)
                                .addComponent(btRefreshMK))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKunciMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btCariMK)
                    .addComponent(btRefreshMK))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCariMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariMKActionPerformed
    cariMK();
    }//GEN-LAST:event_btCariMKActionPerformed

    private void btRefreshMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshMKActionPerformed
    tampilmk();        // TODO add your handling code here:
    }//GEN-LAST:event_btRefreshMKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCariMK;
    private javax.swing.JButton btRefreshMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBMK;
    private javax.swing.JTextField tfKunciMK;
    // End of variables declaration//GEN-END:variables
}
