/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
import java.sql.*;
import javax.swing.JOptionPane;
import lib.koneksi;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
/**
 *
 * @author ASUS VIVOBOOK
 */
public class FTambahDosen extends javax.swing.JInternalFrame {
    koneksi konek = new koneksi ();
    private ActionEvent evt;

    /**
     * Creates new form FTambahDosen
     */
    public FTambahDosen() {
        initComponents();
        btRefreshDsnActionPerformed(evt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfNIDN = new javax.swing.JTextField();
        tfNamaDosen = new javax.swing.JTextField();
        tfTempatLahir = new javax.swing.JTextField();
        dcTanggal = new com.toedter.calendar.JDateChooser();
        tfJK = new javax.swing.JTextField();
        tfAlamat = new javax.swing.JTextField();
        tfNoTlp = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfPendidikan = new javax.swing.JTextField();
        tfKonsentrasi = new javax.swing.JTextField();
        tfPangkat = new javax.swing.JTextField();
        tfGolongan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBDosen = new javax.swing.JTable();
        btSimpan = new javax.swing.JButton();
        btRefreshDsn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Form Tambah Dosen");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TAMBAH DOSEN");

        jLabel2.setText("NIDN ");

        jLabel3.setText("Nama Dosen");

        jLabel4.setText("Tempat Lahir");

        jLabel5.setText("Tanggal Lahir");

        jLabel6.setText("Jenis Kelamin");

        jLabel7.setText("Alamat");

        jLabel8.setText("No. Tlp");

        jLabel9.setText("Email");

        jLabel10.setText("Pendidikan Terakhir");

        jLabel11.setText("Konsentrasi");

        jLabel12.setText("Pangkat");

        jLabel13.setText("Golongan");

        tfJK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJKActionPerformed(evt);
            }
        });

        jTBDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "NIDN", "Nama Dosen", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Alamat", "No.Tlp", "Email", "Pendidikan Terakhir", "Konsentrasi", "Pangkat", "Golongan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTBDosen);

        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        btRefreshDsn.setText("Refresh");
        btRefreshDsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshDsnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNIDN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dcTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfJK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfGolongan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPangkat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfKonsentrasi, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPendidikan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(tfNoTlp))
                                .addGap(184, 184, 184))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel6)))))
                                .addGap(18, 18, 18)
                                .addComponent(btSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btRefreshDsn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNIDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dcTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSimpan)
                            .addComponent(btRefreshDsn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfKonsentrasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRefreshDsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshDsnActionPerformed
        DefaultTableModel tabeldosen = new DefaultTableModel(); 
        tabeldosen.addColumn("No");
        tabeldosen.addColumn("ID");
        tabeldosen.addColumn("NIDN");
        tabeldosen.addColumn("Nama Dosen");
        tabeldosen.addColumn("Tempat Lahir");
        tabeldosen.addColumn("Tanggal Lahir");
        tabeldosen.addColumn("Jenis Kelamin");
        tabeldosen.addColumn("Alamat");
        tabeldosen.addColumn("No. Tlp");
        tabeldosen.addColumn("Email");
        tabeldosen.addColumn("Pendidikan Terakhir");
        tabeldosen.addColumn("Konsentrasi");
        tabeldosen.addColumn("Pangkat");
        tabeldosen.addColumn("Golongan");
    try{ //PENGUJIAN
        String sql = "Select * from daftar_dosen ";
        Statement st = konek.getKoneksi().createStatement();
        ResultSet hasil = st.executeQuery(sql);
        int no = 0;
        while(hasil.next()){
            no = no + 1;
            tabeldosen.addRow(new Object[]{no, hasil.getString(1), hasil.getString(2), hasil.getString(3), hasil.getString(4), hasil.getString(5), hasil.getString(6), hasil.getString(7), hasil.getString(8), hasil.getString(9), hasil.getString(10), hasil.getString(11), hasil.getString(12), hasil.getString(13)});
        }
    jTBDosen.setModel(tabeldosen);
        }catch(Exception e){//JIKA TIDAK BERHASIL
        JOptionPane.showMessageDialog(this, "Kesalahan : " + e);
    
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_btRefreshDsnActionPerformed

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        String nidn = tfNIDN.getText();
        String nama_dosen = tfNamaDosen.getText(); 
        String tempat_lahir = tfTempatLahir.getText();
        String tgl_lahir = new SimpleDateFormat("yyyy-MM-dd").format(dcTanggal.getDate());
        String jenis_kelamin = tfJK.getText();
        String alamat = tfAlamat.getText();
        String no_hp = tfNoTlp.getText();
        String email = tfEmail.getText();
        String pendidikan_terakhir = tfPendidikan.getText();
        String konsentrasi = tfKonsentrasi.getText();
        String pangkat = tfPangkat.getText();
        String golongan = tfGolongan.getText();
   
        if (!nidn.isEmpty() && !nama_dosen.isEmpty()) {
        String sql = "INSERT INTO daftar_dosen(nidn, nama_dosen, tempat_lahir, tgl_lahir, jenis_kelamin, alamat, no_hp, email, pendidikan_terakhir, konsentrasi, pangkat, golongan) VALUES('"+nidn+"', '"+nama_dosen+"', '"+tempat_lahir+"', '"+tgl_lahir+"', '"+jenis_kelamin+"', '"+alamat+"', '"+no_hp+"', '"+email+"', '"+pendidikan_terakhir+"', '"+konsentrasi+"', '"+pangkat+"', '"+golongan+"')"; 
        try {
            Statement s = konek.getKoneksi().createStatement();
            s.executeUpdate(sql);
            s.close();
            JOptionPane.showMessageDialog(this, "Data Dosen Berhasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Dosen Gagal Disimpan: " + e);
        }
    } else {
        JOptionPane.showMessageDialog(this, "NIDN dan Nama Dosen harus di isi dengan benar." ); 
    }
        this.btRefreshDsnActionPerformed(evt);
        tfNIDN.setText("");
        tfNamaDosen.setText("");
        tfTempatLahir.setText("");
        tfJK.setText("");
        tfAlamat.setText("");
        tfNoTlp.setText("");
        tfEmail.setText("");
        tfPendidikan.setText("");
        tfKonsentrasi.setText("");
        tfPangkat.setText("");
        tfGolongan.setText("");
 
        
        
        
    }//GEN-LAST:event_btSimpanActionPerformed

    private void tfJKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRefreshDsn;
    private javax.swing.JButton btSimpan;
    private com.toedter.calendar.JDateChooser dcTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBDosen;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfGolongan;
    private javax.swing.JTextField tfJK;
    private javax.swing.JTextField tfKonsentrasi;
    private javax.swing.JTextField tfNIDN;
    private javax.swing.JTextField tfNamaDosen;
    private javax.swing.JTextField tfNoTlp;
    private javax.swing.JTextField tfPangkat;
    private javax.swing.JTextField tfPendidikan;
    private javax.swing.JTextField tfTempatLahir;
    // End of variables declaration//GEN-END:variables
}
