/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author ASUS VIVOBOOK
 */

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lib.koneksi;

public class FTampilMahasiswa extends javax.swing.JInternalFrame {
    koneksi konek = new koneksi ();

    /**
     * Creates new form FTampilMahasiswa
     */
    public FTampilMahasiswa() {
        initComponents();
        tampilmahasiswa();
    }
    
    public void tampilmahasiswa() {
        DefaultTableModel tabelmahasiswa = new DefaultTableModel();
        tabelmahasiswa.addColumn("No");
        tabelmahasiswa.addColumn("ID");
        tabelmahasiswa.addColumn("NIM");
        tabelmahasiswa.addColumn("Nama Mahasiswa");
        tabelmahasiswa.addColumn("Tempat Lahir");
        tabelmahasiswa.addColumn("Tanggal Lahir");
        tabelmahasiswa.addColumn("Jenis Kelamin");
        tabelmahasiswa.addColumn("Alamat");
        tabelmahasiswa.addColumn("No. Tlp");
        tabelmahasiswa.addColumn("Email");
        tabelmahasiswa.addColumn("Asal Sekolah");
        tabelmahasiswa.addColumn("Jurusan");
        tabelmahasiswa.addColumn("Orang Tua");
        
        
    try{ //PENGUJIAN
        String sql = "Select * from daftar_mahasiswa ";
        Statement st = konek.getKoneksi().createStatement();
        ResultSet hasil = st.executeQuery(sql);
        int no = 0;
        while(hasil.next()){
            no = no + 1;
            tabelmahasiswa.addRow(new Object[]{no, hasil.getString(1), hasil.getString(2), hasil.getString(3), hasil.getString(4), hasil.getString(5), hasil.getString(6), hasil.getString(7), hasil.getString(8), hasil.getString(9), hasil.getString(10), hasil.getString(11), hasil.getString(12)});
        }
    jTBMahasiswa.setModel(tabelmahasiswa);
        }catch(Exception e){//JIKA TIDAK BERHASIL
        JOptionPane.showMessageDialog(this, "Kesalahan : " + e);
    
        }
    }
    
    private void carimahasiswa(){
        DefaultTableModel tabelmahasiswa = new DefaultTableModel();
        tabelmahasiswa.addColumn("No");
        tabelmahasiswa.addColumn("ID");
        tabelmahasiswa.addColumn("NIM");
        tabelmahasiswa.addColumn("Nama Mahasiswa");
        tabelmahasiswa.addColumn("Tempat Lahir");
        tabelmahasiswa.addColumn("Tanggal Lahir");
        tabelmahasiswa.addColumn("Jenis Kelamin");
        tabelmahasiswa.addColumn("Alamat");
        tabelmahasiswa.addColumn("No. Tlp");
        tabelmahasiswa.addColumn("Email");
        tabelmahasiswa.addColumn("Asal Sekolah");
        tabelmahasiswa.addColumn("Jurusan");
        tabelmahasiswa.addColumn("Orang Tua");
    try{ //PENGUJIAN
        String sql = "Select * from daftar_mahasiswa where nama_mhs LIKE'%"+tfKunciMhs.getText()+"%'";
        Statement st = konek.getKoneksi().createStatement();
        ResultSet hasil = st.executeQuery(sql);
        int no = 0;
        while(hasil.next()){
            no = no + 1;
            tabelmahasiswa.addRow(new Object[]{no, hasil.getString(1), hasil.getString(2), hasil.getString(3), hasil.getString(4), hasil.getString(5), hasil.getString(6), hasil.getString(7), hasil.getString(8), hasil.getString(9), hasil.getString(10), hasil.getString(11), hasil.getString(12)});
        }
        jTBMahasiswa.setModel(tabelmahasiswa);
        }catch(Exception e){//JIKA TIDAK BERHASIL
        JOptionPane.showMessageDialog(this, "Kesalahan : " + e);
    
        }
    }            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfKunciMhs = new javax.swing.JTextField();
        btCari = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBMahasiswa = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Form Data Mahasiswa");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DATA MAHASISWA");

        jLabel2.setText("Cari Nama Mahasiswa");

        btCari.setText("Cari");
        btCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariActionPerformed(evt);
            }
        });

        btRefresh.setText("Refresh");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        jTBMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID", "NIM", "Nama Mahasiswa", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Alamat", "No. Tlp", "Email", "Asal Sekolah", "Jurusan", "Orang Tua"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTBMahasiswa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tfKunciMhs)
                .addGap(18, 18, 18)
                .addComponent(btCari)
                .addGap(18, 18, 18)
                .addComponent(btRefresh)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(367, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfKunciMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCari)
                    .addComponent(btRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
    tampilmahasiswa();        // TODO add your handling code here:
    }//GEN-LAST:event_btRefreshActionPerformed

    private void btCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariActionPerformed
    carimahasiswa();        // TODO add your handling code here:
    }//GEN-LAST:event_btCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCari;
    private javax.swing.JButton btRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBMahasiswa;
    private javax.swing.JTextField tfKunciMhs;
    // End of variables declaration//GEN-END:variables
}
