/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author ASUS VIVOBOOK
 */

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lib.koneksi;

public class FTampilDosen extends javax.swing.JInternalFrame {
    koneksi konek = new koneksi ();

    /**
     * Creates new form FTampilDosen
     */
    public FTampilDosen() {
        initComponents();
        tampildosen();
    }
    
    public void tampildosen() {
        DefaultTableModel tabeldosen = new DefaultTableModel();
        tabeldosen.addColumn("No");
        tabeldosen.addColumn("ID");
        tabeldosen.addColumn("NIDN");
        tabeldosen.addColumn("Nama Dosen");
        tabeldosen.addColumn("Tempat Lahir");
        tabeldosen.addColumn("Tanggal Lahir");
        tabeldosen.addColumn("Jenis Kelamin");
        tabeldosen.addColumn("Alamat");
        tabeldosen.addColumn("No. Tlp");
        tabeldosen.addColumn("Email");
        tabeldosen.addColumn("Pendidikan Terakhir");
        tabeldosen.addColumn("Konsentrasi");
        tabeldosen.addColumn("Pangkat");
        tabeldosen.addColumn("Golongan");
    try{ //PENGUJIAN
        String sql = "Select * from daftar_dosen ";
        Statement st = konek.getKoneksi().createStatement();
        ResultSet hasil = st.executeQuery(sql);
        int no = 0;
        while(hasil.next()){
            no = no + 1;
            tabeldosen.addRow(new Object[]{no, hasil.getString(1), hasil.getString(2), hasil.getString(3), hasil.getString(4), hasil.getString(5), hasil.getString(6), hasil.getString(7), hasil.getString(8), hasil.getString(9), hasil.getString(10), hasil.getString(11), hasil.getString(12), hasil.getString(13)});
        }
    jTBDosen.setModel(tabeldosen);
        }catch(Exception e){//JIKA TIDAK BERHASIL
        JOptionPane.showMessageDialog(this, "Kesalahan : " + e);
    
        }
    }
    
    private void cari() {
        DefaultTableModel tabeldosen = new DefaultTableModel();
        tabeldosen.addColumn("No");
        tabeldosen.addColumn("ID");
        tabeldosen.addColumn("NIDN");
        tabeldosen.addColumn("Nama Dosen");
        tabeldosen.addColumn("Tempat Lahir");
        tabeldosen.addColumn("Tanggal Lahir");
        tabeldosen.addColumn("Jenis Kelamin");
        tabeldosen.addColumn("Alamat");
        tabeldosen.addColumn("No. Tlp");
        tabeldosen.addColumn("Email");
        tabeldosen.addColumn("Pendidikan Terakhir");
        tabeldosen.addColumn("Konsentrasi");
        tabeldosen.addColumn("Pangkat");
        tabeldosen.addColumn("Golongan");
    try{ //PENGUJIAN
        String sql = "Select * from daftar_dosen where nama_dosen LIKE'%"+tfKunciDosen.getText()+"%'";
        Statement st = konek.getKoneksi().createStatement();
        ResultSet hasil = st.executeQuery(sql);
        int no = 0;
        while(hasil.next()){
            no = no + 1;
            tabeldosen.addRow(new Object[]{no, hasil.getString(1), hasil.getString(2), hasil.getString(3), hasil.getString(4), hasil.getString(5), hasil.getString(6), hasil.getString(7), hasil.getString(8), hasil.getString(9), hasil.getString(10), hasil.getString(11), hasil.getString(12), hasil.getString(13)});
        }
        jTBDosen.setModel(tabeldosen);
        }catch(Exception e){//JIKA TIDAK BERHASIL
        JOptionPane.showMessageDialog(this, "Kesalahan : " + e);
    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfKunciDosen = new javax.swing.JTextField();
        btCariDosen = new javax.swing.JButton();
        btRefreshDosen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBDosen = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Form Data Dosen");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DATA DOSEN");

        jLabel2.setText("Cari Nama Dosen :");

        tfKunciDosen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfKunciDosenKeyPressed(evt);
            }
        });

        btCariDosen.setText("Cari");
        btCariDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariDosenActionPerformed(evt);
            }
        });

        btRefreshDosen.setText("Refresh");
        btRefreshDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshDosenActionPerformed(evt);
            }
        });

        jTBDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID", "NIDN", "Nama Dosen", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Alamat", "No. Tlp", "Email", "Pendidikan Terakhir", "Konsentrasi", "Pangkat", "Golongan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTBDosen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfKunciDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btCariDosen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRefreshDosen))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1077, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKunciDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCariDosen)
                    .addComponent(btRefreshDosen)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCariDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariDosenActionPerformed
    cari();        // TODO add your handling code here:
    }//GEN-LAST:event_btCariDosenActionPerformed

    private void btRefreshDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshDosenActionPerformed
    tampildosen();        // TODO add your handling code here:
    }//GEN-LAST:event_btRefreshDosenActionPerformed

    private void tfKunciDosenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKunciDosenKeyPressed
     // TODO add your handling code here:
    }//GEN-LAST:event_tfKunciDosenKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCariDosen;
    private javax.swing.JButton btRefreshDosen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBDosen;
    private javax.swing.JTextField tfKunciDosen;
    // End of variables declaration//GEN-END:variables
}
